/* GUNS workstation: Gateway data, human-reviewed setups, local paper orders only. */
(function(root){'use strict';root.GunsUI={create:function(a){
 const C=root.Guns,W=root.GunsWorkflow,cache=new Map(),evidence=new Map(),jobs=new Set(),times={},errors={};let selected=null,rows=[],results=[],news=[],newsMeta={},articleText='',depth=null,setup=1,lastConfirm=-Infinity,bookId=a.state().bookId;
 const tutorial=root.GunsTutorial.create({bindings:()=>W.bindings(E.cfg())});
 function analyze(d,q,s,n){const p=C.analyze(d,q,E.cfg(),s,n,a.now());p.tick=d?.minTick;return p;}
 const E=root.GunsExecution({...a,validate:o=>analyze(cache.get(o.symbol),a.quotes()[o.conid],o.guns.setup,o.guns.notes)});
 const esc=a.esc,px=x=>Number.isFinite(x)?a.px(x):'—',money=x=>Number.isFinite(x)?a.money(x):'—';
 function put(id,html){const el=document.getElementById(id);if(el&&el.innerHTML!==html)el.innerHTML=html;}
 function notes(){if(!selected)return {};const k=C.day(a.now())+':'+selected.symbol,b=E.book();return b.notes[k]||(b.notes[k]={});}
 function plan(s=setup,preview=false){return analyze(cache.get(selected?.symbol),a.quotes()[selected?.conid],s,preview?{...notes(),chartSetup:s}:notes());}
 function verifyCandidate(row){if(!row||jobs.has('verify'))return;job('verify',async()=>{times['verify:'+row.conid]=a.now();const data=await request('guns_verify',{conid:row.conid});if(Number(data.conid)!==Number(row.conid))throw Error('Verification contract mismatch');evidence.set(row.conid,data);if(evidence.size>60)evidence.delete(evidence.keys().next().value);});}
 function tutorialOpen(){if(E.exposure()){errors.arm='Cancel / flatten GUNS exposure before entering the isolated tutorial.';live();return;}tutorial.open();}
 function openArticle(index){const n=news[index],sym=selected?.symbol,bid=bookId;if(!n?.articleId)return;articleText='Loading licensed article…';job('article',async()=>{const j=await request('guns_article',{newsProvider:n.provider,articleId:n.articleId});if(selected?.symbol!==sym||bookId!==bid)return;articleText=j.text||j.warning||'No readable article returned.';if(j.text){notes().newsEvidence={provider:n.provider,articleId:n.articleId,headline:n.headline,time:n.time,openedAt:a.now()};a.save();}});}
 async function request(kind,params={}){const ctl=new AbortController(),timer=setTimeout(()=>ctl.abort(),40000);try{const r=await fetch('/data/'+kind+'?'+new URLSearchParams({provider:'tws',...params}),{signal:ctl.signal});if(!r.ok)throw Error('HTTP '+r.status);const j=await r.json();if(j.error)throw Error(j.error);return j;}finally{clearTimeout(timer);}}
 function job(key,fn){if(jobs.has(key))return;jobs.add(key);times[key]=a.now();Promise.resolve().then(fn).then(()=>{delete errors[key];}).catch(e=>{errors[key]=e.message||'Request failed';}).finally(()=>{jobs.delete(key);live();});}
 function scan(){if(!a.usingTws()){errors.scan='Select IB Gateway data source';live();return;}job('scan',async()=>{rows=(await request('guns_scan')).rows||[];a.sync();});}
 function bars(sym){if(a.now()-(times['bars:'+sym]||0)>2500)job('bars:'+sym,async()=>{cache.set(sym,await request('guns_bars',{symbol:sym}));if(cache.size>8)cache.delete(cache.keys().next().value);});}
 function choose(inst){if(!inst)return;selected={...inst,secType:'STK',exch:'SMART',mult:1,brokerId:true};news=[];newsMeta={};articleText='';depth=null;delete errors.arm;a.render();a.sync();bars(selected.symbol);}
 function instruments(){return [...(selected?[{...selected,priority:3}]:[]),...E.book().active.map(b=>({...b.inst,priority:3})),...E.pending().map(o=>({...o,priority:3})),...(a.tab()==='guns'?rows.map(x=>({...x,priority:1})):[])];}
 function confirmSetup(s){if(!selected||tutorial.isOpen()||a.now()-lastConfirm<500)return;lastConfirm=a.now();setup=Number(s);const n={...notes(),chartSetup:setup,chartReviewedAt:a.now()},p=analyze(cache.get(selected.symbol),a.quotes()[selected.conid],setup,n),r=E.arm(p,selected,n);errors.arm=r.errors.join(' · ');a.render();live();}
 function pulse(){if(bookId!==a.state().bookId){bookId=a.state().bookId;selected=null;cache.clear();news=[];newsMeta={};articleText='';depth=null;}
  if(a.usingTws()){const symbols=new Set(E.pending().map(o=>o.symbol));if(a.tab()==='guns'&&selected&&!tutorial.isOpen())symbols.add(selected.symbol);symbols.forEach(bars);
   if(a.tab()==='guns'&&!tutorial.isOpen()){if(a.now()-(times.scan||0)>30000)scan();verifyCandidate([selected,...rows.slice(0,6)].find(x=>x&&a.now()-(times['verify:'+x.conid]||0)>65000));if(selected){const sym=selected.symbol,bid=bookId;
    if(a.now()-(times['news:'+sym]||0)>30000)job('news:'+sym,async()=>{const j=await request('guns_news',{symbol:sym});if(selected?.symbol===sym&&bookId===bid){news=j.rows||[];newsMeta=j;}});
    if(a.now()-(times['depth:'+sym]||0)>5000)job('depth:'+sym,async()=>{const j=await request('depth',{symbol:sym});if(selected?.symbol===sym&&bookId===bid)depth=j;});
   }}
  }E.pulse();live();
 }
 function exportData(){const blob=new Blob([JSON.stringify({version:C.VERSION,exportedAt:a.now(),paperOnly:true,cloudCollector:false,books:E.g().books},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='guns-paper-research.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 function input(id,label,value,min,max,step){return '<label>'+label+'<input id="guns-'+id+'" type="number" value="'+esc(value)+'" min="'+min+'" max="'+max+'" step="'+step+'"></label>';}
 function check(id,label,value){return '<label class="guns-check"><input id="guns-'+id+'" type="checkbox" '+(value?'checked':'')+'>'+label+'</label>';}
 function view(){const c=E.cfg(),n=notes();return `<section id="guns-workspace"><header class="guns-header"><div><small>STRATEGY WORKSTATION / LONG STOCKS</small><h1>GUNS <span>Execution desk</span></h1></div><div><b>PAPER ONLY</b> <button data-guns="tutorial">Guided tutorial</button> <button data-guns="scan">Scan now</button> <button data-guns="export">Export research</button></div></header><p class="guns-warning">Browser + Paper Desk + Gateway must stay running. Stops are simulated, not broker-held. Gaps/slippage can exceed planned risk. Cloud / post-exit collection is not connected.</p>
 <section class="guns-grid"><aside class="guns-panel"><h2>01 / Discovery</h2><form id="guns-search"><input id="guns-symbol" aria-label="Stock search" placeholder="Stock symbol"><button>Find</button></form><div id="guns-search-results"></div><p class="guns-muted">Preliminary US gainers. Independently verify the selected stock and first six broker candidates, paced one at a time. Other rows remain unverified. Numerical attention score = volume (40) + gap (30) + tight spread (30); not a chart-quality or profit prediction.</p><div id="guns-scanner"></div><details><summary>Selected stock: source & coverage</summary><div id="guns-evidence"></div></details></aside>
 <section class="guns-market"><article class="guns-panel"><div id="guns-quote"></div><small id="guns-clock"></small></article><article class="guns-panel"><h2>02 / Price structure</h2><small>EMA 9 (blue) · EMA 20 (gold) · SMA 50 (purple) · SMA 200 (white)</small><h3>1 MINUTE</h3><canvas id="guns-chart-1"></canvas><h3>5 MINUTE</h3><canvas id="guns-chart-5"></canvas><h3>DAILY</h3><canvas id="guns-chart-d"></canvas></article><section class="guns-context"><article class="guns-panel"><h2>Headlines</h2><div id="guns-news-meta"></div><div id="guns-news"></div><pre id="guns-article" aria-live="polite"></pre></article><article class="guns-panel"><h2>Level II / displayed size</h2><div id="guns-depth"></div></article></section></section>
 <aside class="guns-panel guns-planner"><h2>03 / Plan & risk</h2><label>Setup<select id="guns-setup">${Object.entries(C.names).map(([id,name])=>`<option value="${id}" ${Number(id)===setup?'selected':''}>S${id} · ${esc(name)}</option>`).join('')}</select></label><div class="guns-fields">${input('risk','Risk / current equity %',c.riskPct,.01,100,.01)}<label>Target<select id="guns-reward"><option value="2" ${c.rewardR==2?'selected':''}>2R</option><option value="2.5" ${c.rewardR==2.5?'selected':''}>2.5R</option></select></label><label>S1/S2 stop<select id="guns-stopmode">${['ATR','PRICE','FIXED'].map(v=>`<option ${c.stopMode===v?'selected':''}>${v}</option>`).join('')}</select></label>${input('atr','ATR period (app default 14)',c.atrPeriod,2,100,1)}${input('fixed','Fixed stop $',c.fixedStop,.01,100,.01)}${input('spread','Max spread $',c.maxSpread,.001,.10,.001)}${input('volume','Premarket minimum volume',c.minVolume,30000,1e10,1000)}</div>${check('be','Move stop to actual entry at +1R (before fees)',c.breakeven)}<div id="guns-risk-live"></div><h3>Human review</h3>${check('common','Corporate common stock verified; not ETF',n.common)}${check('catalyst','Favorable catalyst reviewed; NOT fixed-price buyout',n.catalyst)}${check('room','Daily overhead resistance / room reviewed',n.room)}<p class="guns-muted">YOU judge chart quality. Pattern hints are advisory, not approval. Float is not verified. Numerical risk/data guards still apply.</p><div class="guns-fields">${input('trigger','Reviewed trigger high (blank = suggested)',n.levels?.[setup]?.trigger??'',.01,1e7,.001)}${setup>=3&&setup<=4?input('candlelow','Reviewed flag candle low (required with override)',n.levels?.[setup]?.candleLow??'',.01,1e7,.001):''}</div><div id="guns-advisories"></div><div id="guns-checklist"></div><p id="guns-error" role="status"></p><div id="guns-entry-buttons"></div><button class="guns-arm" data-guns="arm">Confirm my S${setup} chart & arm paper entry</button><small>No automatic new-entry approval. S1–S4 buttons confirm that specific setup, using its reviewed or suggested levels. Changed pending trigger/stop requires re-arming.</small><details><summary>Entry keyboard shortcuts</summary><p>Default 1–4 or unique Alt+letter/digit. Click a field, then press your chord. Some Alt chords are browser-reserved. Shortcuts never run while editing or in other tabs/dialogs.</p><div class="guns-fields">${W.bindings(c).map((key,i)=>`<label>S${i+1}<input data-guns-key="${i}" aria-label="S${i+1} shortcut" readonly value="${esc(key)}"></label>`).join('')}</div></details></aside></section>
 <section class="guns-panel guns-review"><h2>04 / Pending & protected positions</h2><div id="guns-active"></div><h2>Trade journal</h2><div id="guns-journal"></div></section></section>`;}
 const chartKeys=new WeakMap();
 function chart(id,bars,levels){const canvas=document.getElementById(id);if(!canvas)return;const width=Math.floor(canvas.clientWidth),height=180,dpr=root.devicePixelRatio||1,key=JSON.stringify([width,bars.length,bars.at(-1),levels]);if(chartKeys.get(canvas)===key)return;chartKeys.set(canvas,key);canvas.width=width*dpr;canvas.height=height*dpr;const ctx=canvas.getContext('2d');ctx.scale(dpr,dpr);ctx.fillStyle='#101923';ctx.fillRect(0,0,width,height);ctx.font='10px monospace';ctx.fillStyle='#8c9eaf';if(!bars.length){ctx.fillText('Waiting for broker history — no synthetic bars',12,30);return;}
  const start=Math.max(0,bars.length-65),v=bars.slice(start),studies=C.studies(bars).map(x=>x.slice(start));let lo=Math.min(...v.map(x=>x.l)),hi=Math.max(...v.map(x=>x.h));const pad=Math.max((hi-lo)*.08,.01);lo-=pad;hi+=pad;const plotW=Math.max(1,width-55),dx=plotW/v.length,y=p=>8+(hi-p)/(hi-lo)*145,x=i=>(i+.5)*dx;
  for(let i=0;i<4;i++){const p=lo+(hi-lo)*i/3;ctx.strokeStyle='#243140';ctx.beginPath();ctx.moveTo(0,y(p));ctx.lineTo(plotW,y(p));ctx.stroke();ctx.fillStyle='#8c9eaf';ctx.fillText(p.toFixed(2),plotW+5,y(p)+3);}
  v.forEach((b,i)=>{ctx.fillStyle=ctx.strokeStyle=b.c>=b.o?'#43c59e':'#ee7379';ctx.beginPath();ctx.moveTo(x(i),y(b.h));ctx.lineTo(x(i),y(b.l));ctx.stroke();ctx.fillRect(x(i)-dx*.28,Math.min(y(b.o),y(b.c)),Math.max(1,dx*.56),Math.max(1,Math.abs(y(b.c)-y(b.o))));});
  studies.forEach((s,j)=>{ctx.strokeStyle=['#68b5ff','#f1bc57','#ba94e8','#eeeeee'][j];ctx.beginPath();let connected=false;s.forEach((p,i)=>{if(p==null||p<lo||p>hi){connected=false;return;}if(!connected)ctx.moveTo(x(i),y(p));else ctx.lineTo(x(i),y(p));connected=true;});ctx.stroke();});
  Object.entries(levels||{}).forEach(([label,p])=>{if(!Number.isFinite(p)||p<lo||p>hi)return;ctx.strokeStyle=label==='stop'?'#ee7379':'#e6bd6a';ctx.setLineDash([4,4]);ctx.beginPath();ctx.moveTo(0,y(p));ctx.lineTo(plotW,y(p));ctx.stroke();ctx.setLineDash([]);ctx.fillStyle=ctx.strokeStyle;ctx.fillText(label+' '+px(p),8,y(p)-3);});
  const stamp=b=>typeof b.t==='string'?b.t:new Date(b.t).toLocaleTimeString('en-US',{timeZone:'America/New_York',hour:'2-digit',minute:'2-digit'});ctx.fillStyle='#8c9eaf';ctx.fillText(stamp(v[0]),5,height-6);ctx.fillText(stamp(v.at(-1))+' ET',Math.max(5,plotW-85),height-6);
 }
 function live(){if(a.tab()!=='guns'||!document.getElementById('guns-workspace'))return;const p=plan(setup,true),q=a.quotes()[selected?.conid]||{},r=E.sizing(p,selected),issues=E.issues(p,selected),d=cache.get(selected?.symbol);
  put('guns-quote','<strong>'+esc(selected?.symbol||'Select a stock')+'</strong><span>LAST '+px(q.last)+'</span><span>BID '+px(q.bid)+'</span><span>ASK '+px(q.ask)+'</span><span class="'+(selected&&a.ready(selected.conid)?'guns-pass':'guns-fail')+'">'+(selected&&a.ready(selected.conid)?'LIVE':'NOT READY')+'</span>');
  put('guns-clock',new Date(a.now()).toLocaleString('en-US',{timeZone:'America/New_York'})+' ET · chart '+(d?Math.max(0,Math.round((a.now()-d.updatedAt)/1000))+'s old':'unavailable'));
  const ranked=W.rank(rows,a.quotes(),evidence,cid=>a.ready(cid),E.cfg(),a.now());
  put('guns-scanner',ranked.length?ranked.map(c=>'<button class="guns-candidate" data-guns-pick="'+c.row.conid+'"><strong>'+esc(c.row.symbol)+'</strong><span>'+px(a.quotes()[c.row.conid]?.last)+'</span><small>'+esc(c.row.name||'Stock candidate')+'</small><small>'+esc(c.eligible?'SCREEN PASS · attention '+c.score:'NOT VERIFIED / SCREEN FAIL: '+c.why.join(' · '))+'</small><small>Gap '+(Number.isFinite(c.gap)?c.gap.toFixed(2)+'%':'unknown')+' · PM '+(Number.isFinite(c.volume)?c.volume.toLocaleString():'unknown')+' · Chart quality: YOUR decision</small></button>').join(''):'<p class="guns-muted">'+(jobs.has('scan')?'Scanning Gateway…':'No scanner candidates yet.')+'</p>');
  const ev=evidence.get(selected?.conid);put('guns-evidence',ev?'<p>'+esc(ev.source)+' · '+esc(new Date(ev.at).toISOString())+'</p><p>Previous RTH close '+px(ev.previousClose)+' on '+esc(ev.previousCloseDate)+' · session '+esc(ev.sessionDate)+'</p><p>'+esc(ev.observedBars)+' observed PM bars · '+esc(ev.volumeUnit)+'</p><p>'+esc(ev.coverage)+'</p>':'Awaiting independent Gateway verification. Unknown is not a pass.');
  put('guns-search-results',results.map((x,i)=>'<button data-guns-search-pick="'+i+'">'+esc(x.symbol)+' · '+esc(x.name)+'</button>').join(''));
  put('guns-risk-live','<div class="guns-budget"><small>CURRENT EQUITY × '+esc(E.cfg().riskPct)+'%</small><strong>'+money(r.budget)+'</strong><span>Equity '+money(r.equity)+'</span></div><dl><dt>Whole shares</dt><dd>'+r.qty+'</dd><dt>Planned risk incl. fees</dt><dd>'+money(r.risk)+'</dd><dt>Unused budget</dt><dd>'+money(r.unused)+'</dd><dt>Entry / limit cap</dt><dd>'+px(p.entry)+' / '+px(p.limit)+'</dd><dt>Stop / target</dt><dd>'+px(p.stop)+' / '+px(p.target)+'</dd><dt>ATR / gap</dt><dd>'+px(p.atr)+' / '+(Number.isFinite(p.gap)?p.gap.toFixed(2)+'%':'—')+'</dd><dt>Premarket volume</dt><dd>'+Number(p.volume||0).toLocaleString()+'</dd></dl><small>Re-sized while pending and before fill. Risk uses limit cap; target re-anchors to actual fill. Fees and whole shares leave budget unused.</small>');
  put('guns-checklist',p.checks.map(c=>c.label==='Chart and setup reviewed by user'?'<div>Your S button confirms chart/setup review.</div>':'<div class="'+(c.ok?'guns-pass':'guns-fail')+'">'+(c.ok?'PASS':'WAIT')+' · '+esc(c.label)+'</div>').join(''));
  put('guns-advisories','<small>Levels: '+esc(p.levelSource||'unavailable')+'</small>'+(p.advisories||[]).map(c=>'<p class="guns-muted">HINT · '+esc(c.label)+' — '+(c.ok?'detected':'not detected; judge yourself')+'</p>').join(''));
  put('guns-entry-buttons',[1,2,3,4].map(s=>{const why=E.issues(plan(s,true),selected);return '<button data-guns-confirm="'+s+'" '+(why.length?'disabled':'')+' title="'+esc(why.join(' · ')||'Your confirmation of '+C.names[s])+'">S'+s+' · '+esc(W.bindings(E.cfg())[s-1])+'<small>'+esc(C.names[s])+'</small></button>';}).join(''));
  put('guns-error',Object.values(errors).filter(Boolean).map(esc).join('<br>')+(issues.length?'<p>'+issues.slice(-4).map(esc).join('<br>')+'</p>':''));const button=document.querySelector('[data-guns="arm"]');if(button)button.disabled=issues.length>0;if(button)button.textContent='Confirm my S'+setup+' chart & arm paper entry';
  put('guns-news-meta','<small>'+esc(newsMeta.source||'IB Gateway API news')+' · '+esc((newsMeta.providers||[]).map(p=>p.name+' ('+p.code+')').join(', ')||'No provider entitlement confirmed')+' · '+esc(newsMeta.at?new Date(newsMeta.at).toISOString():'not received')+'</small><p>'+esc(newsMeta.warning||'API entitlements may differ from TWS. Opening an article does not approve the catalyst.')+'</p>');
  put('guns-news',news.length?news.map((n,i)=>'<p><small>'+esc(n.provider)+' · '+esc(n.time)+'</small>'+esc(n.headline)+(n.articleId?' <button data-guns-article="'+i+'">Read article</button>':'')+'</p>').join(''):'<p class="guns-muted">No headlines received. This is not proof that no news exists. Review catalyst independently.</p>');
  put('guns-article',esc(articleText));
  put('guns-depth',depth?'<table><thead><tr><th>Bid size</th><th>Bid</th><th>Ask</th><th>Ask size</th></tr></thead><tbody>'+Array.from({length:Math.max(depth.bids?.length||0,depth.asks?.length||0)},(_,i)=>'<tr><td>'+esc(depth.bids?.[i]?.size??'—')+'</td><td>'+px(depth.bids?.[i]?.price)+'</td><td>'+px(depth.asks?.[i]?.price)+'</td><td>'+esc(depth.asks?.[i]?.size??'—')+'</td></tr>').join('')+'</tbody></table>':'<p class="guns-muted">Depth unavailable. No inferred liquidity.</p>');
  const pending=E.pending().map(o=>'<article><b>'+esc(o.symbol)+' · S'+o.guns.setup+' · pending</b> '+o.qty+' shares / budget '+money(o.guns.budgetAtFill??o.guns.budgetAtArm)+' <button data-guns-cancel="'+esc(o.id)+'">Cancel</button></article>').join('');
  const active=E.book().active.map(b=>'<article><b>'+esc(b.inst.symbol)+' · S'+b.setup+' · '+b.qty+' shares</b> Entry '+px(b.entry)+' / Stop '+px(b.stop)+' / Target '+px(b.target)+' '+(b.stopTriggered?'STOP LATCHED ':'')+'<button data-guns-flat="'+esc(b.id)+'">Flatten paper position</button></article>').join('');put('guns-active',pending+active||'<p class="guns-muted">No pending entries or protected positions.</p>');
  put('guns-journal',E.book().journal.slice(0,30).map(b=>'<article><b>'+esc(b.inst.symbol)+' · S'+b.setup+'</b> Net '+money(b.net)+' / '+b.actualR.toFixed(2)+'R · '+new Date(b.closedAt).toLocaleString()+'<small>Sampled bid range '+px(b.minBid)+'–'+px(b.maxBid)+' · '+b.events.length+' lifecycle events</small></article>').join('')||'<p class="guns-muted">Closed trades appear here. Export all lifecycle events as JSON. Browser-local storage, not a cloud archive.</p>');
  const minute=(d?.minute||[]).filter(b=>b.t+60000<=a.now()),levels={entry:p.entry,stop:p.stop,target:p.target};chart('guns-chart-1',minute,levels);chart('guns-chart-5',C.aggregate(minute,5).filter(b=>b.t+300000<=a.now()),levels);chart('guns-chart-d',d?.daily||[],{});
 }
 document.addEventListener('submit',e=>{if(e.target.id!=='guns-search')return;e.preventDefault();const text=document.getElementById('guns-symbol').value.trim();if(text)job('search',async()=>{results=((await request('search',{q:text})).results||[]).filter(x=>x.type==='STK');});});
 document.addEventListener('click',e=>{const el=e.target.closest('[data-guns],[data-guns-confirm],[data-guns-article],[data-guns-pick],[data-guns-search-pick],[data-guns-cancel],[data-guns-flat]');if(!el||el.disabled||tutorial.isOpen())return;if(el.hasAttribute('data-guns-confirm'))confirmSetup(el.dataset.gunsConfirm);else if(el.hasAttribute('data-guns-article'))openArticle(Number(el.dataset.gunsArticle));else if(el.hasAttribute('data-guns-pick'))choose(rows.find(x=>x.conid===Number(el.dataset.gunsPick)));else if(el.hasAttribute('data-guns-search-pick'))choose(results[Number(el.dataset.gunsSearchPick)]);else if(el.hasAttribute('data-guns-cancel'))a.cancel(el.dataset.gunsCancel);else if(el.hasAttribute('data-guns-flat'))E.flatten(el.dataset.gunsFlat);else if(el.dataset.guns==='scan')scan();else if(el.dataset.guns==='export')exportData();else if(el.dataset.guns==='tutorial')tutorialOpen();else if(el.dataset.guns==='arm')confirmSetup(setup);});
 document.addEventListener('keydown',e=>{if(a.tab()!=='guns'||document.hidden||tutorial.isOpen()||document.querySelector('dialog[open]'))return;const key=W.chord(e),field=e.target.closest?.('[data-guns-key]');if(field){if(e.key==='Tab')return;e.preventDefault();const b=W.setBinding(W.bindings(E.cfg()),Number(field.dataset.gunsKey),key);if(b){E.g().config.shortcuts=b;field.value=key;delete errors.keys;a.save();}else errors.keys='Use a unique 1–4 or Alt+letter/digit shortcut.';live();return;}if(e.target.closest?.('input,textarea,select,button,[contenteditable]:not([contenteditable="false"])'))return;const i=W.bindings(E.cfg()).indexOf(key);if(i>=0){e.preventDefault();confirmSetup(i+1);}});
 const configFields={risk:'riskPct',reward:'rewardR',stopmode:'stopMode',atr:'atrPeriod',fixed:'fixedStop',spread:'maxSpread',volume:'minVolume',be:'breakeven'};
 document.addEventListener('change',e=>{const el=e.target;if(!el.id?.startsWith('guns-'))return;const id=el.id.slice(5);if(id==='setup'){setup=Number(el.value);a.render();}else if(id==='trigger'||id==='candlelow'){if(!selected)return;if(el.value!==''&&(!el.checkValidity()||!Number.isFinite(Number(el.value)))){errors.levels='Enter a positive reviewed price, or clear for suggested levels.';live();return;}delete errors.levels;const n=notes();n.levels=n.levels||{};n.levels[setup]=n.levels[setup]||{};n.levels[setup][id==='trigger'?'trigger':'candleLow']=el.value===''?null:Number(el.value);delete n.chartSetup;}else if(['common','catalyst','room'].includes(id)){if(selected)notes()[id]=el.checked;}else if(configFields[id]){if(el.type==='number'&&(!el.checkValidity()||!Number.isFinite(Number(el.value)))){errors.config='Enter a valid value within the displayed range';live();return;}delete errors.config;E.g().config[configFields[id]]=el.type==='checkbox'?el.checked:id==='stopmode'?el.value:Number(el.value);}a.save();live();});
 root.addEventListener('resize',live);setInterval(pulse,1000);
 return {view,live,pulse,instruments,execution:E,choose};
}};})(window);
