const test=require('node:test'),a=require('node:assert/strict'),V=require('./vmi.js');
const base={method:'FCF',base:100,cash:20,debt:10,shares:10,fx:1,adr:1,g1:0,g2:0,g3:0,discount:0};
function company(){const c=V.company('ABC','USD');c.metrics={years:10,growth:10,moats:3,roe:16,roic:15,current:2,debtEbitda:2,service:20,cet1:11,gearing:39};for(const k of Object.keys(V.reviews))c.reviews[k]={status:'PASS',note:'Dated evidence'};delete c.reviews.upfront;c.price={value:90,date:'2026-01-01',currency:'USD',source:'fixture'};for(const m of Object.keys(V.rules))c.valuations[m]={iv:100,date:'2026-01-01',source:'fixture'};return c;}
test('Collections separate quality from price and entry timing',()=>{const c=company();a.equal(V.collection(c,'moderate'),'opportunities');c.reviews.entry.status='UNKNOWN';a.equal(V.collection(c,'moderate'),'opportunities');c.price.value=120;a.equal(V.collection(c,'moderate'),'qualified');c.metrics.moats=0;a.equal(V.collection(c,'moderate'),'research');});
test('Automatic financials retain provenance, exclude stale inputs and preserve adopted IV',()=>{const c=company(),before=JSON.stringify(c);const d={symbol:'ABC',currency:'USD',retrievedAt:Date.now(),metrics:{roe:25,service:3},staleMetrics:['service'],sources:['https://example.test/filing'],valuationInputs:{...base,forecast:12,basis:'Annual FCF, not TTM',flowPeriod:'2025-12-31'}};const next=V.automatic(c,d,10);a.equal(JSON.stringify(c),before);a.equal(next.metrics.roe,25);a.equal(next.metrics.service,null);a.equal(next.valuations.moderate.iv,100);a.equal(next.automatic.scenarios.length,3);a.equal(next.reviews.moat.note,'Dated evidence');a.throws(()=>V.automatic(c,{...d,symbol:'OTHER'}));a.throws(()=>V.automatic(c,d,0));const empty=V.automatic(V.company('ABC','USD'),d,10);a.ok(empty.valuations.moderate.automatic);a.ok(empty.valuations.moderate.source.includes('not TTM'));const w=V.workspace();w.companies.push(empty);a.deepEqual(V.validate(JSON.stringify(w)),w);});
test('DCF has 20 flows, no terminal, correct FX/ADR and rejects missing inputs',()=>{const r=V.dcf(base,'moderate');a.equal(r.iv,201);a.equal(r.rows.length,20);a.equal(r.terminalValue,0);a.equal(V.dcf({...base,fx:2,adr:8},'moderate').iv,3216);a.equal(V.dcf({...base,g2:50},'moderate').rows[5].growth,15);for(const x of [{shares:0},{base:-1},{cash:null},{discount:NaN},{g1:-100}])a.throws(()=>V.dcf({...base,...x},'moderate'));});
test('DCF preset assumptions, five-year capex and OCF eligibility are explicit',()=>{const r=V.scenarios(base,[10,20,30]);a.deepEqual(r.map(x=>x.inputs.g1),[10,20,30]);a.deepEqual(r.map(x=>x.inputs.g2),[5,20,30]);a.deepEqual(r.map(x=>x.inputs.g3),[2,4,4]);a.equal(V.dcf({...base,method:'NORMALIZED',ocf:100,capex:[10,20,30,40,50]},'moderate').base,70);const q=V.scenarios({...base,method:'OCF',ocf:150,ni:100},[10,12,14]);a.ok(q[0].error&&q[1].error);a.ok(!q[2].error);});
test('PEG and PSG use distinct source boundaries; NAV uses no multiple',()=>{a.equal(V.ratio({method:'PSG',ratio:2,growth:10}).classification,'Fairly priced');a.equal(V.ratio({method:'PSG',ratio:3,growth:10}).classification,'Fairly priced');a.equal(V.ratio({method:'PSG',ratio:3.1,growth:10}).classification,'Overvalued');a.equal(V.ratio({method:'PEG',ratio:15,growth:10}).classification,'Reasonable rough guide');a.equal(V.multiple({method:'NAV',base:100,shares:10,fx:1,adr:1}).iv,10);});
test('Missing evidence stays unknown; quality, value, entry cannot compensate each other',()=>{a.equal(V.screen(V.company('ABC','USD'),'moderate').stage,'RESEARCH');const c=company();a.equal(V.screen(c,'moderate').stage,'REVIEW COMPLETE');c.price.value=100;a.equal(V.screen(c,'moderate').stage,'WAIT FOR VALUE');c.price.value=90;c.reviews.entry.status='UNKNOWN';a.equal(V.screen(c,'moderate').stage,'WAIT FOR ENTRY');c.metrics.moats=2;a.equal(V.screen(c,'moderate').stage,'QUALITY FLAG');});
test('Strict/inclusive profitability and debt boundaries; all debt inputs required',()=>{const c=company();c.metrics.roe=15;a.equal(V.screen(c,'conservative').steps[3].status,'FAIL');a.equal(V.screen(c,'moderate').steps[3].status,'PASS');c.metrics.current=1;c.metrics.debtEbitda=3;a.equal(V.screen(c,'moderate').steps[4].status,'FAIL');a.equal(V.screen(c,'optimistic').steps[4].status,'PASS');c.metrics.service=null;a.equal(V.screen(c,'optimistic').steps[4].status,'UNKNOWN');});
test('Sector-specific rules and speculative track-record policies',()=>{const c=company();c.sector='bank';c.metrics.roic=null;c.metrics.cet1=10;a.equal(V.screen(c,'moderate').steps[3].status,'PASS');a.equal(V.screen(c,'moderate').steps[4].status,'FAIL');c.sector='reit';c.metrics.gearing=45;a.equal(V.screen(c,'optimistic').steps[4].status,'PASS');a.equal(V.screen(c,'moderate').steps[4].status,'FAIL');c.category='speculative';Object.assign(c.metrics,{cfoQuarters:1,niYears:0,niQuarters:0});a.equal(V.screen(c,'optimistic').steps[0].status,'PASS');a.equal(V.screen(c,'moderate').steps[0].status,'FAIL');});
test('Tranches conserve budget and fees, reject invalid supports, retain spent allowance',()=>{const x={capital:100000,count:20,factor:1,spent:0,cash:5000,fee:1,iv:100,levels:[90,80,70,60]};const r=V.allocate(x);a.ok(r.total<=5000&&r.tranches.every(t=>Number.isInteger(t.qty)));a.equal(V.allocate({...x,spent:5000}).total,0);a.equal(V.allocate({...x,iv:60}).total,0);a.throws(()=>V.allocate({...x,levels:[90,90,80]}));a.throws(()=>V.allocate({...x,count:7}));});
test('Covered call caps upside and rejects uncovered contracts; leveraged paths differ',()=>{const x={owned:100,contracts:1,deliverable:100,cost:50,strike:55,premium:2,fees:5};a.equal(V.coveredCall(x).maxProfit,695);a.equal(V.coveredCall(x).maxLoss,4805);a.throws(()=>V.coveredCall({...x,owned:99}));const bars=[{date:'2020-01-01',close:100},{date:'2020-01-02',close:110},{date:'2020-01-03',close:100}];const r=V.leverage(bars,3,0);a.equal(r.terminal,1);a.ok(r.reset<1);a.throws(()=>V.history([...bars,bars[0]]));a.equal(V.averages(bars)[0].value,null);});
test('SEC filing cutoff, future restatements, conflicting values and quarterly exclusion',()=>{const f={start:'2020-01-01',end:'2020-12-31',val:100,filed:'2021-02-01',form:'10-K',accn:'0000000123-21-000001'},raw=rows=>({cik:123,facts:{'us-gaap':{NetIncomeLoss:{units:{USD:rows}}}}});a.equal(V.sec(raw([f,{...f,filed:'2022-02-01',val:110}]),'2021-12-31').facts.income[0].val,100);a.equal(V.sec(raw([f,{...f,val:101}]),'2022-01-01').facts.income.length,0);a.equal(V.sec(raw([{...f,start:'2020-10-01'}]),'2022-01-01').facts.income.length,0);});
test('Independent planners, immutable event payloads, archive roundtrip and malformed imports',()=>{const w=V.workspace();w.portfolios.defensive.mode='conservative';a.equal(w.portfolios.growth.mode,'moderate');const c=company();w.companies.push(c);w.selected=c.symbol;V.append(w,'test',c);c.metrics.roe=99;a.equal(w.events[0].payload.metrics.roe,16);a.deepEqual(V.validate(JSON.stringify({workspace:w})),w);a.throws(()=>V.validate('{"__proto__":{}}'));w.portfolios.growth.count=0;a.throws(()=>V.validate(JSON.stringify(w)));});
