(function(root){'use strict';
const C=root.VMI,esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),today=()=>new Date().toISOString().slice(0,10);
const fmt=x=>C.finite(x)?x.toLocaleString(undefined,{maximumFractionDigits:3}):'Unknown';
const options=(values,current)=>values.map(x=>'<option value="'+esc(x)+'"'+(x===current?' selected':'')+'>'+esc(x)+'</option>').join('');
const table=(headers,rows)=>'<div class="vmi-scroll"><table><thead><tr>'+headers.map(x=>'<th>'+esc(x)+'</th>').join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+r.map(x=>'<td>'+esc(x)+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>';
const field=(name,label,type='number',value='')=>({name,label,type,value});
const source=()=>field('source','Sources / periods / method rationale (required)','text');
const asof=()=>field('date','As-of date','date',today());
const methods=values=>field('method','Method',values,values[0]);
const conversion=()=>[field('shares','Shares outstanding (same scale as amounts)'),field('fx','Listing currency per statement currency','number',1),field('adr','Underlying shares per listed share / ADR','number',1)];
root.VMIUI={create(adapter){
 let W=C.workspace(),page='today',el=null,message='',dirty=false,busy=false,lastRefresh=0,epoch=0,query='',sourcePage=0;
 const drafts=new Map(),pending=new Set(),results=new Map(),seen=new Map();
 const calls=root.VMICalls.create(adapter);
 let missedPreview=null,missedRevision=0,missedBusy=false;
 function invalidateMissed(){missedRevision++;missedPreview=null;const p=el?.querySelector('#vmi-missed-preview');if(p)p.remove();}
 function missedView(){
  const p=missedPreview?.prepared;
  return '<aside class="vmi-notice">Record an already executed hypothetical paper trade in the current account. This is not a broker order or strategy enrollment. Complete retained long-only stock history is required; active managed positions and affected working orders must be reconciled first.</aside>'+tool('vmi-missed','Record missed paper trade · '+adapter.currentBook().name,[field('symbol','Ticker','text'),field('side','Side',['BUY','SELL'],'BUY'),field('qty','Whole shares'),field('price','Execution price USD'),field('fees','Total fees USD','number',0),field('executedAt','Execution time with UTC offset (e.g. 2026-10-01T14:30:00-04:00)','text'),field('reason','Reason / paper execution evidence','textarea')],'Preview accounting — no recording yet')+(p?'<section id="vmi-missed-preview" class="vmi-card"><h3>Confirm accounting · '+esc(missedPreview.bookName)+'</h3>'+table(['Measure','Before','After','Change'],[['Cash',fmt(p.cashBefore),fmt(p.cashAfter),fmt(p.cashDelta)],['Realized P&L',fmt(p.realizedBefore),fmt(p.realizedAfter),fmt(p.realizedDelta)],['Shares',p.positionBefore?.qty||0,p.positionAfter.qty,p.trade.side+' '+p.trade.qty],['Average cost',fmt(p.positionBefore?.avgCost||0),fmt(p.positionAfter.avgCost),'Replayed chronologically']])+table(['Later trade','Execution','Old realized','New realized'],p.laterTradeChanges.map(x=>[x.tradeId,x.executedAt,fmt(x.before),fmt(x.after)]))+'<p>'+esc(p.trade.symbol+' · '+p.input.executedAt+' · '+p.trade.side+' '+p.trade.qty+' @ '+p.trade.price+' · fees '+p.trade.commission)+'</p><ul>'+p.warnings.map(x=>'<li>'+esc(x)+'</li>').join('')+'</ul><p>All later retained cashAfter values are adjusted by '+esc(fmt(p.cashDelta))+'. Original affected rows are retained in the audit. A full local account backup is saved before recording.</p><button data-action="record-missed">Confirm and record paper trade</button></section>':'')+'<section class="vmi-card"><h3>Historical correction audit · current paper book</h3>'+((adapter.corrections?.()||[]).slice().reverse().map(a=>'<details><summary>'+esc(a.trade.symbol+' · '+a.trade.side+' '+a.trade.qty+' · executed '+a.executionInput+' · recorded '+a.recordedAt)+'</summary><pre>'+esc(JSON.stringify(a,null,2))+'</pre></details>').join('')||'<p>No historical corrections recorded.</p>')+'</section>';
 }
 const company=()=>W.companies.find(c=>c.symbol===W.selected),book=()=>W.portfolios[W.profile],mode=()=>book().mode;
 const key=id=>[W.profile,W.selected,id].join(':');
 const discoveries=new Map(),factRetries=new Map();let scanBusy=false,factsBusy=false,scanPage=0,nextScan=0,scanMode='',bucket='all',dataStatus='Automatic discovery starting…';
 async function request(path){const r=await fetch(path,{signal:AbortSignal.timeout(100000)});if(!r.ok)throw Error('Data HTTP '+r.status);const d=await r.json();if(d.error)throw Error(d.error);return d;}
 function updated(){const status=el?.querySelector('#vmi-data-status');if(status)status.textContent=dataStatus;if(!el?.contains(document.activeElement)||!document.activeElement?.matches('input,textarea,select'))draw();}
 async function discover(){
  if(scanBusy||document.hidden||!adapter.active())return;
  if(scanMode!==mode()){scanMode=mode();scanPage=0;nextScan=0;}
  if(Date.now()<nextScan)return;scanBusy=true;nextScan=Date.now()+120000;const gen=epoch,m=mode();
  try{const d=await request('/data/vmi_scan?mode='+m+'&page='+scanPage);if(gen!==epoch||m!==mode())return;
   for(const row of d.rows)if(!discoveries.has(row.symbol)&&discoveries.size<1000)discoveries.set(C.ticker(row.symbol),{...row,source:d.source});
   scanPage=d.nextPage;dataStatus=discoveries.size+' listings discovered · next page '+(scanPage+1)+' · '+new Date(d.retrievedAt).toLocaleTimeString();
  }catch(e){dataStatus='Discovery retry in two minutes: '+e.message;}finally{scanBusy=false;updated();}
 }
 async function acquire(){
  if(factsBusy||document.hidden||!adapter.active())return;
  const selected=company(),tracked=selected?[selected,...W.companies.filter(c=>c!==selected)]:W.companies;
  const candidate=[...tracked,...Array.from(discoveries.values()).slice(0,100)].find(c=>(!c.currency||c.currency==='USD')&&Date.now()-(factRetries.get(c.symbol)||0)>300000&&Date.now()-(c.automatic?.retrievedAt||0)>21600000);
  if(!candidate)return;factsBusy=true;factRetries.set(candidate.symbol,Date.now());const gen=epoch;
  try{const d=await request('/data/vmi_fundamentals?symbol='+encodeURIComponent(candidate.symbol));if(gen!==epoch)return;
   const current=W.companies.find(c=>c.symbol===candidate.symbol),next=C.automatic(current||C.company(candidate.symbol,'USD'),d,W.autoDiscount||10);
   if(current){event('automatic-fundamentals',{symbol:current.symbol,observation:d});Object.assign(current,next);}else Object.assign(candidate,{candidate:next,automatic:d});
   candidate.automatic=d;candidate.dataError=null;dataStatus='Retrieved financials: '+candidate.symbol+' · '+new Date(d.retrievedAt).toLocaleTimeString();
  }catch(e){candidate.dataError=e.message;dataStatus=candidate.symbol+' retry in five minutes: '+e.message;}finally{factsBusy=false;updated();}
 }
 function openDiscovered(symbol){let c=W.companies.find(c=>c.symbol===symbol);if(!c){if(W.companies.length>=100)throw Error('100-company archive limit. Export before starting another workspace.');c=discoveries.get(symbol)?.candidate?C.copy(discoveries.get(symbol).candidate):C.company(symbol,'USD');event('company-added',c);W.companies.push(c);}W.selected=symbol;page='review';lastRefresh=0;draw();protect(refresh)();protect(acquire)();}
 function discoveryView(){const counts={research:0,qualified:0,opportunities:0};W.companies.forEach(c=>counts[C.collection(c,mode())]++);return '<section class="vmi-summary">'+[['all','All tracked',W.companies.length],['research','Research',counts.research],['qualified','Qualified · waiting for value',counts.qualified],['opportunities','Qualified + undervalued',counts.opportunities]].map(([id,label,n])=>'<button data-bucket="'+id+'" aria-pressed="'+(bucket===id)+'"><strong>'+n+'</strong>'+esc(label)+'</button>').join('')+'</section><section class="vmi-card"><h3>Automatic market discovery</h3><p id="vmi-data-status" role="status">'+esc(dataStatus)+'</p><p>Valuation-neutral US-listed prefilter. A page loads every two minutes while VMI is visible. Up to 1,000 listings; financials acquired sequentially for the first 100 plus your tracked companies. No GUNS chart subscriptions are used.</p><div class="vmi-discovery">'+Array.from(discoveries.values()).slice(-100).map(r=>'<article><button data-discovered="'+esc(r.symbol)+'">'+esc(r.symbol)+'</button><span>ROE '+esc(r.fields?.ROE||'—')+' · ROIC '+esc(r.fields?.ROIC||'—')+'</span><small>'+esc(r.automatic?'Filings retrieved':r.dataError?'Retry scheduled':'Financial retrieval queued')+'</small></article>').join('')+'</div><p>Click to track a listing and retain its financial observations in your research export. Discovery-only observations remain session-only. Qualified companies pass all five business gates; opportunities additionally pass the value gate. Entry timing is separate. Financial retrieval does not invent moat evidence.</p></section>';}
 function acquiredView(c){return c.automatic?'<section class="vmi-card"><h3>Retrieved financial evidence</h3><p>'+esc(c.automatic.name)+' · CIK '+esc(c.automatic.cik)+' · '+esc(new Date(c.automatic.retrievedAt).toLocaleString())+'</p><p>Automatic proposals use annual FCF, not TTM, one provider forecast and an editable '+esc(W.autoDiscount||10)+'% discount rate. No adopted manual valuation is overwritten. Review suitability before treating a proposal as intrinsic value.</p><details><summary>Sources, periods, formulas and calculations</summary><pre>'+esc(JSON.stringify(c.automatic,null,2))+'</pre></details></section>':'<p>Automatic SEC/market financial retrieval is queued for this company.</p>';}

 function notice(s){message=s;const n=el?.querySelector('#vmi-message');if(n)n.textContent=s;}
 function protect(fn){return async(...args)=>{try{await fn(...args);}catch(e){notice(e.message||String(e));}};}
 function event(type,payload){C.append(W,type,payload);dirty=true;}
 const data=f=>Object.fromEntries(new FormData(f)),number=x=>String(x??'').trim()===''?null:Number(x),list=x=>String(x).split(',').map(s=>number(s.trim()));
 function validDate(d){if(!C.date(d)||d>today())throw Error('Valid as-of date no later than today required');}
 function sourced(d){validDate(d.date);if(!d.source.trim())throw Error('Source evidence required');}
 function tool(id,title,fields,submit='Apply / calculate'){
  const d=drafts.get(key(id))||{};
  return '<section class="vmi-card"><h3>'+esc(title)+'</h3><form id="'+id+'"><div class="vmi-grid">'+fields.map(f=>{const v=d[f.name]??f.value;return '<label>'+esc(f.label)+(Array.isArray(f.type)?'<select name="'+f.name+'">'+options(f.type,v)+'</select>':f.type==='textarea'?'<textarea name="'+f.name+'">'+esc(v)+'</textarea>':'<input name="'+f.name+'" type="'+f.type+'" '+(f.type==='number'?'step="any" ':'')+'value="'+esc(v)+'">')+'</label>';}).join('')+'</div><button>'+esc(submit)+'</button></form>'+resultHTML(id)+'</section>';
 }
 function resultHTML(id){const r=results.get(key(id));if(!r)return '';if(id==='vmi-dcf')return table(['Preset','IV','Growth 1–5','Growth 6–10','Growth 11–20','Eligibility'],r.map(v=>[v.preset,fmt(v.iv),v.inputs.g1,Math.min(v.inputs.g2,15),v.inputs.g3,v.error||'Calculated']))+'<details><summary>Full calculation trail</summary><pre>'+esc(JSON.stringify(r,null,2))+'</pre></details>';return '<pre>'+esc(JSON.stringify(r,null,2))+'</pre>';}
 function rulesView(){const r=C.policy(mode());return '<details class="vmi-card"><summary>Active numeric rules and source references</summary>'+table(['Rule','Active cutoff','Reference lines'],[
 ['ROE / ROIC',(r.strictRoe?'>':'≥')+r.roe+'% / ≥'+r.roic+'%','4485–4505'],['Consistent history',r.years+' years','4240–4295'],['Debt ratios',(r.strictCurrent?'>':'≥')+'1 current; '+(r.strictDebt?'<':'≤')+'3 debt/EBITDA; <30% service','1886–1916; 4536–4559; 6724'],['Debt pass policy',r.debtPasses+' of 3; every input required','1916; 2495'],['Banks / REIT','CET1 >10%; gearing '+(r.strictGear?'<':'≤')+r.gear+'%','4554–4559'],['OCF alternative','≤ '+r.ocf+' × positive NI','2845–2848; 5657'],['Speculative','Profitable years '+r.niYears+'; NI quarters '+r.niQuarters+'; OCF quarters '+r.cfoQuarters,'4280–4295; 6218'],['Risky size',fmt(r.riskySize)+' × full allocation','5884–5889'],['PEG / PSG','PEG ≤1.5 reasonable; PSG 0.2–0.3 fair','2615; 3160–3167']])+'<p>Presets select stricter or looser source alternatives. Their combinations are app policies, not named course strategies. Conservative DCF combines lowest forecast, halved second-stage growth and 2% late growth; moderate averages and optimistic takes the highest, both using 4% late growth. No numeric disagreement is automatically sent to review.</p></details>';}
 function todayView(){return discoveryView()+tool('vmi-auto-settings','Automatic valuation assumptions',[field('discount','Discount rate % (editable app default)','number',W.autoDiscount||10)],'Recalculate proposals')+'<section class="vmi-card"><h3>Your research queue</h3><p>Daily: inspect dated prices and supports. Quarterly: refresh filings, moat and valuation. Track discoveries above or add companies below. Financial statements are retrieved automatically with dates and sources.</p>'+table(['Company','Category','Stage','Price / date','Next review'],W.companies.filter(c=>bucket==='all'||C.collection(c,mode())===bucket).map(c=>[c.symbol,c.category,C.screen(c,mode()).stage,c.price?fmt(c.price.value)+' '+c.currency+' / '+c.price.date:'Unknown',c.nextReview?(c.nextReview<=today()?'DUE · ':'')+c.nextReview:'Not set']))+'</section>'+tool('vmi-add','Add a listing',[field('symbol','Ticker','text'),field('currency','Listing currency','text','USD')],'Add company')+rulesView();}
 function reviewView(c){const screening=C.screen(c,mode());return tool('vmi-stock-ticket','Prepare stock BUY ticket · '+adapter.currentBook().name,[field('qty','Whole shares'),field('limit','Limit price ('+c.currency+')','number',c.price?.value??'')],'Open in Trade — no submission')+'<p>The target is the currently selected paper account, not a research planner. Review the contract, quantity, price and account in Trade before clicking BUY.</p>'+acquiredView(c)+'<section class="vmi-card"><h3>'+esc(c.symbol+' · '+screening.stage)+'</h3>'+screening.steps.map(s=>'<details open><summary><span class="vmi-status '+s.status+'">'+s.status+'</span> '+esc(s.name)+'</summary><ul>'+s.checks.map(x=>'<li>'+esc(x.status+' · '+x.label)+(x.details?'<ul>'+x.details.map(d=>'<li>'+esc(d.status+' · '+d.label)+'</li>').join('')+'</ul>':'')+'</li>').join('')+'</ul></details>').join('')+'<p>Speculative firms may not pass ordinary profitability gates; they are never mislabeled ordinary quality passes. Their first-year/two-quarter/one-OCF-quarter track-record policies and reduced sizing remain explicit. Banks/property/commodity businesses may omit OCF consistency in their written track-record review.</p></section>'+tool('vmi-metrics','Financial and quality inputs',[field('category','Category',C.categories,c.category),field('sector','Sector exception',C.sectors,c.sector),...Object.entries(C.metrics).map(([k,v])=>field(k,v,'number',c.metrics[k]??'')),source()],'Apply metrics')+tool('vmi-evidence','Evidence-based review',[field('item','Review item',Object.keys(C.reviews),'track'),field('status','Conclusion',['UNKNOWN','PASS','FAIL'],'UNKNOWN'),field('note','Written evidence and source','textarea')],'Save evidence')+table(['Item','Status','Evidence'],Object.entries(c.reviews).map(([k,v])=>[C.reviews[k],v.status,v.note]))+tool('vmi-notes','Reminders and observations',[field('nextReview','Next review','date',c.nextReview),field('notes','Notes','textarea',c.notes)],'Save notes')+tool('vmi-sec','SEC import metadata',[field('cik','Independently verified issuer CIK','text'),field('cutoff','Filing-date cutoff','date',today())],'Prepare official URL')+'<section class="vmi-card"><label>Import downloaded CompanyFacts JSON<input id="vmi-sec-file" type="file" accept=".json"></label><p>Verify issuer CIK and listing/share class yourself. Annual USD US-GAAP only; no automatic download or conversion into TTM. Custom/IFRS tags, debt, ROIC and forecasts are not guessed. Filing date is not exact SEC acceptance time.</p>'+(c.financials?'<h4>'+esc(c.financials.entity)+'</h4>'+table(['Metric','Period end','USD value','Tag','Filed'],Object.entries(c.financials.facts).flatMap(([k,rows])=>rows.map(f=>[k,f.end,fmt(f.val),f.tag,f.filed])))+'<p>'+esc(c.financials.warnings.join('; '))+'</p>':'')+'</section>';}
 function valueView(c){return '<aside class="vmi-notice">Amounts and shares must use the SAME scale (e.g. millions). Capex = positive outflows. Latest-quarter cash and debt; latest 12-month flow, unless explicitly normalizing. Growth forecasts need dated sources. No terminal value is added.</aside>'+tool('vmi-price','Dated reference price',[field('value','Price','number',c.price?.value??''),asof(),source()],'Apply price')+tool('vmi-dcf','20-year discounted valuation',[methods(['FCF','NORMALIZED','OCF','NI']),field('base','Starting FCF / net income'),field('ocf','Operating cash flow'),field('ni','Net income (OCF eligibility)'),field('capex','Five annual capex outflows, comma-separated','text'),field('cash','Cash and investments'),field('debt','Total debt'),...conversion(),field('forecasts','Forecast growth %, comma-separated','text'),field('discount','Discount rate %'),asof(),source()],'Calculate 3 scenarios')+tool('vmi-multiple','P/B, P/S or NAV value',[methods(['PB','PS','NAV']),field('base','Tangible book, annual sales, or NAV'),field('multiple','Historical comparison multiple','number',1),...conversion(),asof(),source()])+tool('vmi-adopt','Adopt IV for active preset',[field('iv','Intrinsic value per listed share'),asof(),source()],'Adopt IV')+table(['Preset','IV','Margin of safety','As of','Source'],Object.entries(c.valuations).map(([m,v])=>[m,fmt(v.iv),c.price?fmt((1-c.price.value/v.iv)*100)+'%':'Unknown',v.date,v.source]))+tool('vmi-ratio','PEG / PSG rough guide',[methods(['PEG','PSG']),field('ratio','P/E for PEG; P/S for PSG'),field('growth','Matching earnings or sales growth %')])+'<p>Book value is not guaranteed liquidation proceeds. Low debt does not make bankruptcy impossible. Historical course examples are not current market data.</p>';}
 function historyView(c){return tool('vmi-history','Historical CSV metadata',[source(),field('adjustment','Adjustment basis',['raw','split-adjusted','total-return-adjusted','unknown'],'unknown')],'Apply metadata')+'<section class="vmi-card"><label>Import completed daily date,close CSV<input id="vmi-history-file" type="file" accept=".csv"></label><p>We do not sweep GUNS’s live chart subscription pool. No invented missing bars. Daily SMA slope is a diagnostic, not a complete entry signal.</p>'+(c.history?table(['Daily SMA','Value','One-session slope'],C.averages(c.history.rows).map(x=>[x.period,fmt(x.value),fmt(x.slope)]))+'<p>'+esc(c.history.rows.length+' observations · '+c.history.rows[0].date+' to '+c.history.rows.at(-1).date+' · '+c.history.source+' · '+c.history.adjustment)+'</p>':'')+'</section><section class="vmi-card"><h3>Entry and exit discipline</h3><ul><li>Quality first, then price below IV, then retracement to support in an uptrend/consolidation.</li><li>Identify 3–4 supports. Wait for a downtrend to stabilize; never buy the whole allocation at once.</li><li>Review moat damage, forced discounting for 2–3 years, or falling market share for two years.</li><li>Also review fraud, changed needs, a materially better opportunity or gross overvaluation. Defensive and high-growth valuation exits differ.</li><li>Do not transfer ETF moving-average exit rules to VMI stocks.</li></ul><p>Reference: Step 7 and monitoring/sale rules, lines 4590–4861 and 6930–7196.</p></section>'+tool('vmi-decision','Record investment decision',[field('reason','Decision, supporting evidence and next action','textarea')],'Record decision');}
 function portfolioView(c){const p=book();return '<aside class="vmi-notice">'+esc(W.profile==='defensive'?'Defensive business focus; covered calls optional.':W.profile==='balanced'?'Defensive/growth mix. 20% CAGR is your aspiration, not a forecast.':'Growth focus. 25–30% CAGR is your aspiration. Losses can exceed a 30–50% drawdown, including total loss.')+' These are three independent research planners, not funded execution accounts. Initial 100,000 / 20 holdings are editable illustrative defaults.</aside>'+tool('vmi-planner','Planner configuration',[field('capital','Intended capital','number',p.capital),field('count','Planned holdings 8–60','number',p.count),field('bookId','Read-only paper-book ID (blank = unlinked)','text',p.bookId)],'Apply planner')+table(['Available book ID','Name'],adapter.books().map(b=>[b.id,b.name]))+(c?tool('vmi-allocation','Support budget · '+c.symbol,[field('spent','Original purchase cost already allocated','number',0),field('cash','Unreserved available cash'),field('fee','Fee per filled tranche','number',0),field('iv','Active-preset IV','number',c.valuations[mode()]?.iv??''),field('levels','3–4 descending support prices','text')],'Save plan'):'<p>Select a company to plan tranches.</p>')+table(['Company','Created','Planned spend'],p.plans.map(x=>[x.symbol,x.date,fmt(x.result.total)]))+'<p>Whole shares only. Plans do not reserve money or authorize purchases. Reconcile other plans before reusing cash. Reduced speculative/turnaround factor = '+fmt(C.policy(mode()).riskySize)+'. Market-value declines do not create new purchase allowance.</p>'+'<section class="vmi-card"><h3>Covered calls from existing positions</h3><button data-page="calls">Open real IB chain and quotes</button></section>'+'<p>Only covered shares modeled. No early exercise, assignment timing, dividends, liquidity or tax model. Supplemental payoff math, not reconstruction of excluded options lessons.</p>'+tool('vmi-leverage','Leverage illustration from imported history',[field('leverage','Multiple','number',3),field('fee','Total fee % of original principal','number',0)])+'<p>Terminal participation with a zero floor differs from reset-every-observation leverage. No issuer credit, knock-outs, barriers, financing or bank-note pricing. Not a point-in-time strategy backtest; price adjustment basis controls dividend treatment.</p>';}
 function library(){const lines=String(root.VMI_SOURCE||'').split(/\r?\n/).map((text,i)=>({text,line:i+1})).filter(x=>!query||x.text.toLowerCase().includes(query.toLowerCase()));sourcePage=Math.min(sourcePage,Math.max(0,Math.ceil(lines.length/100)-1));return tool('vmi-search','Search your course',[field('query','Search phrase','text',query)],'Search')+'<section class="vmi-card"><p>Original notes; company examples and broad tax/safety claims are not independently verified current facts. '+lines.length+' matching lines, page '+(sourcePage+1)+'.</p><button data-action="prev">Previous</button> <button data-action="next">Next</button><pre>'+esc(lines.slice(sourcePage*100,sourcePage*100+100).map(x=>x.line+'  '+x.text).join('\n'))+'</pre></section>';}
 function draw(){if(!el?.isConnected)return;const c=company();let content=page==='calls'?calls.view():page==='missed'?missedView():page==='today'?todayView():page==='portfolio'?portfolioView(c):page==='learn'?library():page==='archive'?'<section class="vmi-card"><h3>'+W.events.length+' / 5,000 research events</h3><p>Export retains raw SEC facts, inputs, calculations, price observations, decisions and linked-book snapshots. Only the latest 100 event headers are shown below. Closed-app intervals cannot be reconstructed.</p>'+table(['#','Recorded','Type'],W.events.slice(-100).reverse().map(e=>[e.sequence,e.recordedAt,e.type]))+'</section>':c?(page==='review'?reviewView(c):page==='value'?valueView(c):historyView(c)):'<p>Add and select a company on Today.</p>';
 el.innerHTML='<header class="vmi-heading"><div><p class="vmi-eyebrow">VALUE MOMENTUM INVESTING</p><h2>Research, then act.</h2><p>Business quality → value → entry. No weighted score overrides a failed gate.</p></div><div class="vmi-controls"><label>Research portfolio<select id="vmi-profile">'+options(C.profiles,W.profile)+'</select></label><label>Rule preset<select id="vmi-mode">'+options(Object.keys(C.rules),mode())+'</select></label></div></header><aside class="vmi-notice">Session-only research: apply forms, then EXPORT before closing; IMPORT to resume. Research never submits orders. Explicit stock handoffs only select a contract and prefill your existing Trade ticket. The account statistics above are NOT planner balances.</aside><div class="vmi-toolbar"><button data-action="export">Export research JSON</button><label>Import archive<input id="vmi-import" type="file" accept=".json"></label><span id="vmi-quote-status" role="status">IB quotes refresh automatically every five minutes while VMI is visible.</span><button data-action="capture">Capture linked books</button></div><p id="vmi-message" role="status">'+esc(message)+'</p><nav>'+[['today','Discovery'],['review','Company review'],['value','Valuation'],['history','Entry & exit'],['portfolio','Portfolios'],['calls','IB covered calls'],['missed','Record missed trade'],['archive','Archive'],['learn','Course library']].map(([id,title])=>'<button data-page="'+id+'" aria-current="'+(page===id?'page':'false')+'">'+title+'</button>').join('')+'</nav><label class="vmi-company">Company<select id="vmi-company"><option value="">Choose listing</option>'+W.companies.map(c=>'<option value="'+esc(c.symbol)+'"'+(c.symbol===W.selected?' selected':'')+'>'+esc(c.symbol+' · '+c.currency)+'</option>').join('')+'</select></label>'+content;
 calls.mount();
 }
 function capture(){for(const p of C.profiles){const id=W.portfolios[p].bookId;if(!id)continue;const snapshot=adapter.snapshot(id);if(!snapshot){notice('Linked book is no longer available: '+p);continue;}const s=JSON.stringify(snapshot);if(seen.get(p)!==s){event('paper-book-snapshot',{profile:p,bookId:id,snapshot});seen.set(p,s);}}}
 async function refresh(force=false){if(busy||!W.companies.length||!force&&Date.now()-lastRefresh<300000)return;busy=true;lastRefresh=Date.now();const gen=epoch;let good=0,bad=0;notice('Refreshing dated IB observations…');try{for(const c of W.companies.slice()){if(gen!==epoch)break;try{const q=await adapter.quote(c.symbol);if(gen!==epoch)break;const t=q.tradeAt??q.at,at=typeof t==='number'?new Date(t<1e12?t*1000:t).toISOString():t;if(q.served_by!=='tws'||!C.positive(q.last)||!at||!Number.isFinite(Date.parse(at))||Date.parse(at)>Date.now()+60000||c.currency!=='USD')throw Error('No timestamped USD-compatible IB last; fallback not promoted');const price={value:q.last,date:new Date(at).toISOString().slice(0,10),at,source:q.source||'IB Gateway',status:q.status||'Unspecified',currency:'USD',retrievedAt:new Date().toISOString()};if(c.price?.at!==price.at||c.price?.value!==price.value)event('quote',{symbol:c.symbol,price});c.price=price;c.quoteError=null;good++;}catch(e){if(gen!==epoch)break;if(c.quoteError!==e.message)event('quote-failure',{symbol:c.symbol,error:e.message});c.quoteError=e.message;bad++;}await new Promise(r=>setTimeout(r,200));}}finally{busy=false;if(gen===epoch){notice(good+' IB observations; '+bad+' unavailable. Automatically checked '+new Date().toLocaleTimeString()+'. Retained quotes keep their original dates.');if(!el?.contains(document.activeElement)||!document.activeElement?.matches('input,textarea,select'))draw();}}}
 function exportArchive(){if(pending.size&&!confirm('Unapplied drafts are NOT exported. Export applied research only? Cancel to apply forms first.'))return;const url=URL.createObjectURL(new Blob([JSON.stringify({kind:'paper-desk-vmi',exportedAt:new Date().toISOString(),workspace:W})],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='paper_desk_vmi_'+today()+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);dirty=pending.size>0;notice('Download requested. Verify the file; unapplied drafts are excluded.');}
 async function submit(f){const id=f.id,k=key(id),d=data(f),n=Object.fromEntries(Object.entries(d).map(([k,v])=>[k,number(v)])),c=company(),p=book(),m=mode();let output;if(W.events.length>=5000)throw Error('Event limit: export first');
 switch(id){
 case 'vmi-missed':{
  if(missedBusy)throw Error('Preview already in progress');missedBusy=true;missedPreview=null;const revision=++missedRevision;
  try{const result=await adapter.previewMissed({...d,qty:n.qty,price:n.price,fees:n.fees,requestId:Array.from(crypto.getRandomValues(new Uint8Array(16)),x=>x.toString(16).padStart(2,'0')).join('')});if(revision!==missedRevision||page!=='missed')throw Error('Inputs or view changed; preview again');missedPreview=result;}finally{missedBusy=false;}break;
 }
 case 'vmi-stock-ticket':{if(!c||c.currency!=='USD')throw Error('A USD listing is required for this IB stock handoff');if(!Number.isSafeInteger(n.qty)||n.qty<=0||!C.positive(n.limit))throw Error('Positive whole shares and limit price required');const generation=epoch,profile=W.profile;event('stock-ticket-request',{symbol:c.symbol,qty:n.qty,limit:n.limit,book:adapter.currentBook()});await adapter.openStock(c.symbol,n.qty,n.limit,()=>epoch===generation&&company()===c&&W.profile===profile);break;}

 case 'vmi-auto-settings':if(!C.positive(n.discount)||n.discount>100)throw Error('Discount rate must be >0 and ≤100');event('automatic-assumptions',{discount:n.discount});W.autoDiscount=n.discount;for(const item of W.companies)if(item.automatic)Object.assign(item,C.automatic(item,item.automatic,n.discount));break;
 case 'vmi-add':{const item=C.company(d.symbol,d.currency.trim().toUpperCase());if(W.companies.length>=100||W.companies.some(c=>c.symbol===item.symbol))throw Error('Duplicate ticker or 100-company limit');event('company-added',item);W.companies.push(item);W.selected=item.symbol;page='review';lastRefresh=0;break;}
 case 'vmi-metrics':{if(!d.source.trim())throw Error('Source and as-of periods required');const values=Object.fromEntries(Object.keys(C.metrics).map(k=>[k,n[k]]));if(Object.values(values).some(v=>v!==null&&!C.finite(v)))throw Error('Finite metrics required');event('metrics',{symbol:c.symbol,source:d.source,metrics:values,category:d.category,sector:d.sector});Object.assign(c,{metrics:values,category:d.category,sector:d.sector});break;}
 case 'vmi-evidence':if(!d.note.trim())throw Error('Written evidence required');event('evidence',{symbol:c.symbol,...d});c.reviews[d.item]={status:d.status,note:d.note};break;
 case 'vmi-notes':if(d.nextReview&&!C.date(d.nextReview))throw Error('Invalid review date');event('notes',{symbol:c.symbol,...d});Object.assign(c,{notes:d.notes,nextReview:d.nextReview});break;
 case 'vmi-price':sourced(d);if(!C.positive(n.value))throw Error('Positive price required');{const price={value:n.value,date:d.date,source:d.source,currency:c.currency};event('manual-price',{symbol:c.symbol,price});c.price=price;}break;
 case 'vmi-dcf':sourced(d);output=C.scenarios({...n,method:d.method,capex:list(d.capex)},list(d.forecasts));event('dcf',{symbol:c.symbol,inputs:d,output});break;
 case 'vmi-multiple':sourced(d);output=C.multiple({...n,method:d.method});event('multiple',{symbol:c.symbol,preset:m,inputs:d,output});break;
 case 'vmi-adopt':sourced(d);if(!C.positive(n.iv))throw Error('Positive IV required');{const value={iv:n.iv,date:d.date,source:d.source};event('adopt-IV',{symbol:c.symbol,preset:m,value});c.valuations[m]=value;}break;
 case 'vmi-ratio':output=C.ratio({...n,method:d.method});event('ratio-guide',{symbol:c.symbol,inputs:d,output});break;
 case 'vmi-planner':if(!C.positive(n.capital)||!Number.isInteger(n.count)||n.count<8||n.count>60)throw Error('Positive capital and 8–60 holdings required');if(d.bookId&&!adapter.books().some(b=>b.id===d.bookId))throw Error('Unknown paper book ID');event('planner-settings',{profile:W.profile,...d});Object.assign(p,{capital:n.capital,count:n.count,bookId:d.bookId});capture();break;
 case 'vmi-allocation':if(p.plans.length>=1000)throw Error('Plan limit reached');output=C.allocate({...n,levels:list(d.levels),capital:p.capital,count:p.count,factor:['speculative','turnaround'].includes(c.category)?C.policy(m).riskySize:1});event('allocation',{profile:W.profile,symbol:c.symbol,preset:m,inputs:d,output,stage:C.screen(c,m).stage});p.plans.push({symbol:c.symbol,date:today(),result:output});break;
 case 'vmi-call':output=C.coveredCall(n);event('covered-call',{profile:W.profile,inputs:d,output});break;
 case 'vmi-leverage':if(!c?.history)throw Error('Select company and import history first');output=C.leverage(c.history.rows,n.leverage,n.fee);event('leverage',{symbol:c.symbol,inputs:d,source:c.history.source,adjustment:c.history.adjustment,output});break;
 case 'vmi-sec':if(!/^\d{1,10}$/.test(d.cik))throw Error('Verified issuer CIK digits required');validDate(d.cutoff);output={url:'https://data.sec.gov/api/xbrl/companyfacts/CIK'+d.cik.padStart(10,'0')+'.json',instructions:'Open this official URL, download the JSON, then import. Listing identity remains user-verified.'};event('sec-metadata',{symbol:c.symbol,...d});break;
 case 'vmi-history':if(!d.source.trim())throw Error('History provenance required');output={...d,instructions:'Import a completed-date CSV with date,close headers.'};event('history-metadata',{symbol:c.symbol,...d});break;
 case 'vmi-decision':if(!d.reason.trim())throw Error('Decision evidence required');event('decision',{symbol:c.symbol,profile:W.profile,...d});output={recorded:true};break;
 case 'vmi-search':query=d.query;sourcePage=0;break;
 }
 pending.delete(k);drafts.set(k,d);if(output)results.set(k,output);draw();if(id==='vmi-add'){protect(refresh)();protect(acquire)();}
 }
 async function importFile(input){const f=input.files[0];if(!f)return;if(f.size>(input.id==='vmi-import'?50000000:25000000))throw Error('File too large');const gen=epoch,c=company(),p=W.profile,meta=drafts.get(key(input.id==='vmi-sec-file'?'vmi-sec':'vmi-history'));const text=await f.text();input.value='';if(gen!==epoch)throw Error('Workspace changed; reselect file');if(input.id==='vmi-import'){const next=C.validate(text);if((dirty||pending.size)&&!confirm('Replace session research? Export current research first.'))return;W=next;epoch++;lastRefresh=0;drafts.clear();results.clear();pending.clear();seen.clear();dirty=false;draw();await refresh();return;}if(!c||company()!==c||p!==W.profile)throw Error('Selection changed during import');
 if(input.id==='vmi-sec-file'){if(!meta||!/^\d{1,10}$/.test(meta.cik))throw Error('Apply verified CIK/cutoff first');validDate(meta.cutoff);const raw=JSON.parse(text,(k,v)=>{if(['__proto__','constructor','prototype'].includes(k))throw Error('Unsafe SEC JSON key');return v;});if(Number(meta.cik)!==raw.cik)throw Error('CIK mismatch');const normalized=C.sec(raw,meta.cutoff);event('sec-companyfacts',{symbol:c.symbol,identity:'User-verified CIK; listing unverified',retrievedAt:new Date().toISOString(),raw,normalized});c.financials=normalized;}
 else{if(!meta?.source?.trim())throw Error('Apply history provenance first');const rows=C.csv(text);if(rows.some(r=>r.date>=today()))throw Error('Only completed dates before today accepted');const h={rows,source:meta.source,adjustment:meta.adjustment,retrievedAt:new Date().toISOString()};event('history-import',{symbol:c.symbol,...h});c.history=h;}draw();notice('Imported. Export to retain this observation.');
 }
 function attach(node){el=node;el.addEventListener('keydown',e=>e.stopPropagation());el.addEventListener('input',e=>{const f=e.target.closest('form');if(f){if(f.id==='vmi-missed')invalidateMissed();drafts.set(key(f.id),data(f));pending.add(key(f.id));dirty=true;}});el.addEventListener('submit',e=>{e.preventDefault();e.stopPropagation();protect(submit)(e.target);});el.addEventListener('change',e=>{e.stopPropagation();protect(async()=>{const t=e.target;if(t.type==='file'){await importFile(t);return;}if(t.id==='vmi-profile'){W.profile=t.value;dirty=true;draw();return;}if(t.id==='vmi-mode'){event('preset',{profile:W.profile,mode:t.value});book().mode=t.value;draw();return;}if(t.id==='vmi-company'){W.selected=t.value||null;draw();return;}const f=t.closest('form');if(f){if(f.id==='vmi-missed')invalidateMissed();drafts.set(key(f.id),data(f));pending.add(key(f.id));dirty=true;}})();});el.addEventListener('click',e=>{e.stopPropagation();protect(async()=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.discovered){openDiscovered(b.dataset.discovered);return;}if(b.dataset.bucket){bucket=b.dataset.bucket;draw();return;}if(b.dataset.page){invalidateMissed();page=b.dataset.page;draw();return;}switch(b.dataset.action){case 'record-missed':{if(!missedPreview)throw Error('Preview again first');if(!confirm('Record this historical PAPER trade and apply the displayed accounting changes? No IB order will be sent.'))return;const result=adapter.recordMissed(missedPreview);invalidateMissed();drafts.delete(key('vmi-missed'));draw();notice('Recorded. Local backup: '+result.backupKey);break;}case 'export':exportArchive();break;case 'capture':capture();notice('Changed linked-book snapshots captured; no account writes.');break;case 'prev':sourcePage=Math.max(0,sourcePage-1);draw();break;case 'next':sourcePage++;draw();break;}})();});draw();protect(refresh)();protect(discover)();protect(acquire)();}
 document.addEventListener('visibilitychange',()=>{if(!document.hidden&&adapter.active())protect(async()=>{capture();await refresh();})();});window.addEventListener('beforeunload',e=>{if(dirty||pending.size){e.preventDefault();e.returnValue='Export VMI research before leaving';}});setInterval(()=>{if(!document.hidden)protect(capture)();},60000);setInterval(()=>{if(!document.hidden&&adapter.active())protect(refresh)();},15000);setInterval(()=>{if(!document.hidden&&adapter.active()){protect(discover)();protect(acquire)();}},10000);
 return {view:()=>'<section id="vmi-root" aria-label="VMI research workspace"></section>',mount(){const node=document.getElementById('vmi-root');if(node&&node!==el)attach(node);}};
}};
})(globalThis);
