/* Pure VMI research calculations; no account, storage or brokerage writes. */
(function(root){'use strict';
const VERSION='vmi-1';
const rules={
 conservative:{roe:15,strictRoe:true,roic:15,years:10,strictCurrent:true,strictDebt:true,debtPasses:3,gear:40,strictGear:true,ocf:1.2,riskySize:1/3,niYears:1,niQuarters:0,cfoQuarters:2,late:2},
 moderate:{roe:12,strictRoe:false,roic:12,years:5,strictCurrent:true,strictDebt:false,debtPasses:3,gear:45,strictGear:true,ocf:1.2,riskySize:.5,niYears:0,niQuarters:2,cfoQuarters:2,late:4},
 optimistic:{roe:12,strictRoe:false,roic:12,years:5,strictCurrent:false,strictDebt:false,debtPasses:2,gear:45,strictGear:false,ocf:1.5,riskySize:.5,niYears:0,niQuarters:0,cfoQuarters:1,late:4}
};
const profiles=['defensive','balanced','growth'],categories=['defensive','growth','speculative','turnaround','cyclical'],sectors=['ordinary','bank','insurance','utility','reit','property','commodity'];
const metrics={years:'Consistent history (years)',growth:'Projected growth %',moats:'Evidenced moat sources (0–5)',roe:'ROE %',roic:'ROIC %',current:'Current ratio',debtEbitda:'Debt / positive EBITDA',service:'Interest / positive OCF %',cet1:'Bank CET1 %',gearing:'REIT debt / assets %',niYears:'Consecutive profitable years',niQuarters:'Consecutive profitable quarters',cfoQuarters:'Consecutive positive OCF quarters'};
const reviews={track:'Revenue / earnings / cash-flow consistency; margin trends',growth:'Dated forecasts and growth catalysts',moat:'Identify moat sources and pricing power',efficiency:'Profitability trends; receivables versus sales; CCC if applicable',debt:'Debt evidence; sector-specific risks',upfront:'Optional current-ratio exception: upfront payments',valuation:'Method suitability, currency, units and fresh inputs',entry:'Uptrend/consolidation, retracement to support',thesis:'Speculative/turnaround thesis; path to sustainable profits'};
const finite=x=>typeof x==='number'&&Number.isFinite(x),positive=x=>finite(x)&&x>0;
const need=(ok,msg)=>{if(!ok)throw Error(msg);},copy=x=>JSON.parse(JSON.stringify(x));
const date=x=>typeof x==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(x)&&Number.isFinite(Date.parse(x))&&new Date(x).toISOString().slice(0,10)===x;
const ticker=x=>{x=String(x).trim().toUpperCase();need(/^[A-Z0-9][A-Z0-9.\-]{0,19}$/.test(x),'Plain listing ticker required');return x;};
function policy(m){need(Object.hasOwn(rules,m),'Unknown preset');return rules[m];}
function dcf(x,m){const r=policy(m);need(['FCF','NORMALIZED','OCF','NI'].includes(x.method),'Invalid method');let base=x.base;
 if(x.method==='NORMALIZED'){need(positive(x.ocf)&&Array.isArray(x.capex)&&x.capex.length===5&&x.capex.every(v=>finite(v)&&v>=0),'Need positive OCF and five nonnegative annual capex outflows');base=x.ocf-x.capex.reduce((a,b)=>a+b,0)/5;}
 if(x.method==='OCF'){need(positive(x.ocf)&&positive(x.ni)&&x.ocf<=x.ni*r.ocf,'OCF must be ≤ '+r.ocf+' × positive NI');base=x.ocf;}
 need(positive(base),'Starting flow must be positive');need(positive(x.shares)&&positive(x.fx)&&positive(x.adr),'Positive shares, FX and ADR factor required');need(finite(x.cash)&&x.cash>=0&&finite(x.debt)&&x.debt>=0,'Nonnegative cash and debt required');need([x.g1,x.g2,x.g3].every(v=>finite(v)&&v>-100&&v<=100)&&finite(x.discount)&&x.discount>=0&&x.discount<=100,'Growth must be >−100 and ≤100; discount 0–100');
 let flow=base,pv=0,rows=[];for(let year=1;year<=20;year++){const growth=year<=5?x.g1:year<=10?Math.min(15,x.g2):x.g3;flow*=1+growth/100;const discounted=flow/(1+x.discount/100)**year;pv+=discounted;rows.push({year,growth,flow,discounted});}
 const iv=(pv+x.cash-x.debt)/x.shares*x.fx*x.adr;need(finite(iv),'Valuation overflow');return {iv,base,pv,terminalValue:0,rows};
}
function scenarios(x,estimates){need(Array.isArray(estimates)&&estimates.length>0&&estimates.length<=10&&estimates.every(v=>finite(v)&&v>-100&&v<=100),'Enter 1–10 growth estimates');return Object.keys(rules).map(m=>{const g=m==='conservative'?Math.min(...estimates):m==='optimistic'?Math.max(...estimates):estimates.reduce((a,b)=>a+b,0)/estimates.length;const inputs={...x,g1:g,g2:m==='conservative'?g/2:g,g3:rules[m].late};try{return {preset:m,inputs,...dcf(inputs,m)};}catch(e){return {preset:m,inputs,error:e.message};}});}
function multiple(x){need(['PB','PS','NAV'].includes(x.method),'Choose PB, PS or NAV');need(positive(x.base)&&positive(x.shares)&&positive(x.fx)&&positive(x.adr)&&(x.method==='NAV'||positive(x.multiple)),'Positive basis, shares, conversion and comparison multiple required');return {iv:x.base/x.shares*(x.method==='NAV'?1:x.multiple)*x.fx*x.adr};}
function ratio(x){need(['PEG','PSG'].includes(x.method)&&positive(x.ratio)&&positive(x.growth),'Choose PEG/PSG with positive matching ratio and growth');const value=x.ratio/x.growth;return {value,classification:x.method==='PSG'?(value<.2?'Undervalued':value<=.3?'Fairly priced':'Overvalued'):(value<1?'Cheap rough guide':value<=1.5?'Reasonable rough guide':'Expensive rough guide'),note:'Rough guide, not an intrinsic valuation'};}
function screen(c,m){const r=policy(m),v=c.metrics;
 const check=(label,value,fn)=>({label,status:!finite(value)?'UNKNOWN':fn(value)?'PASS':'FAIL'});
 const review=k=>({label:reviews[k],status:c.reviews[k]?.note?.trim()&&['PASS','FAIL'].includes(c.reviews[k]?.status)?c.reviews[k].status:'UNKNOWN'});
 const group=(name,checks)=>({name,checks,status:checks.some(x=>x.status==='FAIL')?'FAIL':checks.some(x=>x.status==='UNKNOWN')?'UNKNOWN':'PASS'});
 const spec=c.category==='speculative';let track=[check('Track record ≥'+r.years+' years',v.years,n=>n>=r.years),review('track')];
 if(spec){track=[{...review('track'),label:'Consistent revenue; evaluate profits under speculative exception'},review('thesis'),check('Positive OCF quarters ≥'+r.cfoQuarters,v.cfoQuarters,n=>Number.isInteger(n)&&n>=r.cfoQuarters)];if(r.niYears)track.push(check('Profitable years ≥'+r.niYears,v.niYears,n=>Number.isInteger(n)&&n>=r.niYears));if(r.niQuarters)track.push(check('Profitable quarters ≥'+r.niQuarters,v.niQuarters,n=>Number.isInteger(n)&&n>=r.niQuarters));}
 const efficiency=[check('ROE '+(r.strictRoe?'>':'≥')+r.roe+'%',v.roe,n=>r.strictRoe?n>r.roe:n>=r.roe),review('efficiency')];if(!['bank','insurance','utility'].includes(c.sector))efficiency.push(check('ROIC ≥'+r.roic+'%',v.roic,n=>n>=r.roic));
 let debt=[review('debt')];if(c.sector==='bank')debt.push(check('CET1 >10%',v.cet1,n=>n>10));else if(c.sector==='reit')debt.push(check('Gearing '+(r.strictGear?'<':'≤')+r.gear+'%',v.gearing,n=>n>=0&&(r.strictGear?n<r.gear:n<=r.gear)));else if(!['insurance','property','commodity'].includes(c.sector)){
  const checks=[check('Current ratio '+(r.strictCurrent?'>':'≥')+'1',v.current,n=>r.strictCurrent?n>1:n>=1),check('Debt / EBITDA '+(r.strictDebt?'<':'≤')+'3',v.debtEbitda,n=>n>=0&&(r.strictDebt?n<3:n<=3)),check('Service <30%, positive OCF denominator',v.service,n=>n<30)];
  if(finite(v.current)&&v.current>=0&&review('upfront').status==='PASS')checks[0]={label:'Documented upfront-payment exception',status:'PASS'};
  debt.push({label:r.debtPasses+' of 3 (all inputs required)',status:checks.some(x=>x.status==='UNKNOWN')?'UNKNOWN':checks.filter(x=>x.status==='PASS').length>=r.debtPasses?'PASS':'FAIL',details:checks});
 }
 const val=c.valuations[m],p=c.price;const value=positive(val?.iv)&&positive(p?.value)&&p.currency===c.currency&&date(p.date)&&date(val.date)?p.value<val.iv?'PASS':'FAIL':'UNKNOWN';
 const steps=[group('1 · Track record',track),group('2 · Growth',[check('Projected growth >0%',v.growth,n=>n>0),review('growth')]),group('3 · Moat',[check('≥3 of 5 supported moat sources',v.moats,n=>Number.isInteger(n)&&n>=3&&n<=5),review('moat')]),group('4 · Profitability',efficiency),group('5 · Debt',debt),group('6 · Value',[{label:'Dated same-currency price < active-preset IV',status:value},review('valuation')]),group('7 · Entry',[review('entry')])];
 const quality=steps.slice(0,5).every(x=>x.status==='PASS');return {steps,quality,stage:!quality?(steps.slice(0,5).some(x=>x.status==='FAIL')?'QUALITY FLAG':'RESEARCH'):steps[5].status!=='PASS'?'WAIT FOR VALUE':steps[6].status!=='PASS'?'WAIT FOR ENTRY':'REVIEW COMPLETE'};
}
function allocate(x){need(positive(x.capital)&&Number.isInteger(x.count)&&x.count>=8&&x.count<=60,'Positive capital; 8–60 whole holdings (8–30 recommended)');need([1,.5,1/3].includes(x.factor),'Full, half or one-third factor required');need([x.spent,x.cash,x.fee].every(v=>finite(v)&&v>=0)&&positive(x.iv),'Nonnegative spent/cash/fee and positive IV required');need(Array.isArray(x.levels)&&[3,4].includes(x.levels.length)&&x.levels.every((v,i)=>positive(v)&&(!i||v<x.levels[i-1])),'Three or four strictly descending supports required');const allowance=x.capital/x.count*x.factor,remaining=Math.max(0,allowance-x.spent),budget=Math.min(remaining,x.cash),part=budget/x.levels.length;const tranches=x.levels.map(price=>{const qty=price<x.iv?Math.max(0,Math.floor((part-x.fee)/price)):0;return {price,qty,cost:qty?qty*price+x.fee:0,eligible:price<x.iv};});return {allowance,remaining,budget,tranches,total:tranches.reduce((s,t)=>s+t.cost,0)};}
function coveredCall(x){need(Number.isInteger(x.owned)&&x.owned>=0&&Number.isInteger(x.contracts)&&x.contracts>0&&Number.isInteger(x.deliverable)&&x.deliverable>0,'Whole shares, contracts and deliverable required');const shares=x.contracts*x.deliverable;need(shares<=x.owned,'Uncovered calls prohibited');need(positive(x.cost)&&positive(x.strike)&&finite(x.premium)&&x.premium>=0&&finite(x.fees)&&x.fees>=0,'Invalid cost, strike, premium or fees');const credit=x.premium*shares-x.fees;return {shares,credit,breakEven:x.cost-credit/shares,maxProfit:(x.strike-x.cost)*shares+credit,maxLoss:x.cost*shares-credit,scenarios:[0,x.cost*.5,x.cost,x.strike,x.strike*1.5].map(price=>({price,pnl:(Math.min(price,x.strike)-x.cost)*shares+credit}))};}
function history(rows){need(Array.isArray(rows)&&rows.length>=2&&rows.length<=30000,'Need 2–30,000 history rows');rows=rows.map(r=>{need(date(r.date)&&positive(r.close),'Invalid historical date/close');return {date:r.date,close:r.close};}).sort((a,b)=>a.date.localeCompare(b.date));need(new Set(rows.map(r=>r.date)).size===rows.length,'Duplicate dates');return rows;}
function csv(text){const lines=text.trim().split(/\r?\n/),head=lines.shift().toLowerCase().split(',').map(x=>x.trim());need(head.includes('date')&&head.includes('close')&&!text.includes('"'),'Unquoted CSV with date,close columns required');return history(lines.map(line=>{const x=line.split(',').map(x=>x.trim());need(x.length===head.length,'Ragged CSV');return {date:x[head.indexOf('date')],close:Number(x[head.indexOf('close')])};}));}
function averages(rows){rows=history(rows);const avg=a=>a.reduce((s,r)=>s+r.close,0)/a.length;return [50,100,150,200].map(n=>({period:n,value:rows.length>=n?avg(rows.slice(-n)):null,slope:rows.length>n?avg(rows.slice(-n))-avg(rows.slice(-n-1,-1)):null}));}
function leverage(rows,lev,fee){rows=history(rows);need(finite(lev)&&lev>=1&&lev<=10&&finite(fee)&&fee>=0&&fee<=100,'Multiple 1–10; total fee 0–100% principal');let reset=1,peak=1,drawdown=0;const first=rows[0].close,path=rows.map((r,i)=>{if(i)reset*=Math.max(0,1+lev*(r.close/rows[i-1].close-1));peak=Math.max(peak,reset);drawdown=Math.min(drawdown,reset/peak-1);return {date:r.date,underlying:r.close/first,reset};});return {underlying:rows.at(-1).close/first,terminal:Math.max(0,1+lev*(rows.at(-1).close/first-1)-fee/100),reset:Math.max(0,reset-fee/100),resetDrawdown:drawdown,path};}
function sec(raw,cutoff){need(date(cutoff)&&raw&&Number.isInteger(raw.cik)&&raw.facts,'CompanyFacts and filing-date cutoff required');const tags={revenue:['RevenueFromContractWithCustomerExcludingAssessedTax','Revenues','SalesRevenueNet'],income:['NetIncomeLoss'],ocf:['NetCashProvidedByUsedInOperatingActivities'],capex:['PaymentsToAcquirePropertyPlantAndEquipment'],equity:['StockholdersEquity']};const out={cik:raw.cik,entity:String(raw.entityName||''),cutoff,facts:{},warnings:[]};for(const [name,alternatives] of Object.entries(tags)){let candidates=[];for(const tag of alternatives){for(const f of raw.facts['us-gaap']?.[tag]?.units?.USD||[]){const days=(Date.parse(f.end)-Date.parse(f.start))/86400000;if(finite(f.val)&&date(f.end)&&date(f.filed)&&f.end<=cutoff&&f.filed<=cutoff&&['10-K','10-K/A','20-F','20-F/A'].includes(f.form)&&/^\d{10}-\d{2}-\d{6}$/.test(f.accn||'')&&(name==='equity'?!f.start:date(f.start)&&days>=330&&days<=380))candidates.push({...f,tag,unit:'USD'});}}
 const facts=[];for(const end of [...new Set(candidates.map(f=>f.end))].sort()){const all=candidates.filter(f=>f.end===end),latest=all.map(f=>f.filed).sort().at(-1),eligible=all.filter(f=>f.filed===latest);if(new Set(eligible.map(f=>JSON.stringify([f.val,f.start||null]))).size!==1){out.warnings.push(name+' '+end+': conflicting values/periods omitted');continue;}facts.push(eligible[0]);}out.facts[name]=facts;if(!facts.length)out.warnings.push(name+': no supported annual USD facts');}return out;}
function company(symbol,currency){need(/^[A-Z]{3}$/.test(currency),'Three-letter currency required');return {symbol:ticker(symbol),currency,category:'growth',sector:'ordinary',metrics:{},reviews:{},valuations:{},price:null,financials:null,history:null,notes:'',nextReview:''};}
function collection(c,m){const s=screen(c,m);return !s.quality?'research':s.steps[5].status==='PASS'?'opportunities':'qualified';}
function automatic(c,d,discount=10){
 need(d&&d.symbol===c.symbol&&d.currency===c.currency,'Financial identity/currency mismatch');
 need(positive(discount)&&discount<=100&&finite(d.retrievedAt),'Invalid valuation assumptions/date');
 const next=copy(c);next.automatic=copy(d);
 for(const [k,v] of Object.entries(d.metrics||{}))if(Object.hasOwn(metrics,k)&&finite(v))next.metrics[k]=d.staleMetrics?.includes(k)?null:v;
 const x=d.valuationInputs;
 if(x&&finite(x.forecast)&&x.forecast>-100&&x.forecast<=100){
  next.automatic.scenarios=scenarios({...x,discount},[x.forecast]);next.automatic.discount=discount;
  for(const r of next.automatic.scenarios)if(positive(r.iv)&&(!next.valuations[r.preset]||next.valuations[r.preset].automatic))next.valuations[r.preset]={iv:r.iv,date:new Date(d.retrievedAt).toISOString().slice(0,10),automatic:true,source:x.basis+'; annual period '+x.flowPeriod+'; discount '+discount+'%; one provider forecast '+x.forecast+'%; '+d.sources.join(' | ')};
 }
 return next;
}
function workspace(){return {schema:VERSION,profile:'balanced',selected:null,companies:[],portfolios:Object.fromEntries(profiles.map(p=>[p,{mode:'moderate',capital:100000,count:20,bookId:'',plans:[]}])),events:[]};}
function append(w,type,payload){
 need(w.events.length<5000,'5,000 event limit: export and start a fresh workspace');
 const entry={sequence:w.events.length+1,type,recordedAt:new Date().toISOString(),payload:copy(payload)};
 const bytes=x=>new TextEncoder().encode(JSON.stringify(x)).byteLength;
 // Allow room for the audit event and its copied current-state projection.
 need(bytes(w)+2*bytes(entry)+1000<49000000,'Archive capacity reached. Export before adding more research.');
 w.events.push(entry);
}
function validate(text){need(typeof text==='string'&&text.length<=50000000,'Archive exceeds 50 MB');const raw=JSON.parse(text,(k,v)=>{need(!['__proto__','constructor','prototype'].includes(k),'Unsafe archive key');return v;}),w=raw.workspace||raw;
 need(w&&w.schema===VERSION&&profiles.includes(w.profile)&&Array.isArray(w.companies)&&w.companies.length<=100&&Array.isArray(w.events)&&w.events.length<=5000,'Invalid archive');const ids=new Set();for(const c of w.companies){need(c&&ticker(c.symbol)===c.symbol&&!ids.has(c.symbol)&&/^[A-Z]{3}$/.test(c.currency)&&categories.includes(c.category)&&sectors.includes(c.sector),'Invalid company');ids.add(c.symbol);need(c.metrics&&c.reviews&&c.valuations&&typeof c.notes==='string'&&typeof c.nextReview==='string','Invalid company fields');for(const [k,v] of Object.entries(c.metrics))need(Object.hasOwn(metrics,k)&&(v===null||finite(v)),'Invalid metric');for(const [k,v] of Object.entries(c.reviews))need(Object.hasOwn(reviews,k)&&v&&['UNKNOWN','PASS','FAIL'].includes(v.status)&&typeof v.note==='string','Invalid evidence');for(const [m,v] of Object.entries(c.valuations))need(Object.hasOwn(rules,m)&&v&&positive(v.iv)&&date(v.date)&&typeof v.source==='string','Invalid IV');if(c.price)need(positive(c.price.value)&&date(c.price.date)&&c.price.currency===c.currency&&typeof c.price.source==='string','Invalid quote');if(c.history){need(typeof c.history.source==='string'&&typeof c.history.adjustment==='string','Invalid history');history(c.history.rows);}if(c.financials)need(c.financials.facts&&Object.values(c.financials.facts).every(a=>Array.isArray(a)&&a.every(f=>f&&finite(f.val)&&date(f.end)&&typeof f.tag==='string'))&&Array.isArray(c.financials.warnings)&&c.financials.warnings.every(x=>typeof x==='string'),'Invalid SEC facts');}
 need(w.selected===null||ids.has(w.selected),'Invalid selected ticker');for(const p of profiles){const b=w.portfolios?.[p];need(b&&Object.hasOwn(rules,b.mode)&&positive(b.capital)&&Number.isInteger(b.count)&&b.count>=8&&b.count<=60&&typeof b.bookId==='string'&&Array.isArray(b.plans)&&b.plans.length<=1000,'Invalid planner');for(const plan of b.plans)need(plan&&ids.has(plan.symbol)&&date(plan.date)&&plan.result&&finite(plan.result.total)&&Array.isArray(plan.result.tranches),'Invalid plan');}for(const [i,e] of w.events.entries())need(e&&e.sequence===i+1&&typeof e.type==='string'&&typeof e.recordedAt==='string'&&Number.isFinite(Date.parse(e.recordedAt)),'Invalid event');return w;
}
const API={VERSION,rules,profiles,categories,sectors,metrics,reviews,finite,positive,date,ticker,copy,policy,dcf,scenarios,multiple,ratio,screen,collection,automatic,allocate,coveredCall,history,csv,averages,leverage,sec,company,workspace,append,validate};if(typeof module==='object'&&module.exports)module.exports=API;root.VMI=API;
})(globalThis);
